spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/walletDb
    username: postgres
    password: 8081
  datasource:
    url: jdbc:postgresql://localhost:5433/walletDb
    username: postgres
    password: 8081
  sql:
    init:
      mode: always
